Skeleton OUnit testsuite for the symbolic executor. OUnit is now required to be installed somewhere in the Ocaml library path (or with camlfind).
Type "make test-cil" at the top-level or "make ounit" in cil/ to run the tests.

No tests yet because I can't find a good entry function at the moment. But anyway, to add test modules, you can create a new module in cil/ounit/, add that module to OUnitMain.ml and Makefile.in. See OUnitSymexeIntegration.ml and my tests in the cilqual/test/TestCilQual directory for examples.

Also, I highly recommend using my customizations in MyOUnit.ml, which provides useful features such as custom logging and running tests in a forked process.

diff --git a/cil/configure b/cil/configure
--- a/cil/configure
+++ b/cil/configure
@@ -672,6 +672,7 @@ target
 target_cpu
 target_vendor
 target_os
+OCAMLFIND
 CPP
 GREP
 EGREP
@@ -3063,6 +3064,89 @@ echo "$as_me: error:
   " >&2;}
    { (exit 1); exit 1; }; }
 fi
+
+
+# find OUnit
+{ echo "$as_me:$LINENO: checking checking for ounit" >&5
+echo $ECHO_N "checking checking for ounit... $ECHO_C" >&6; }
+
+# first try ocamlfind
+# Extract the first word of "ocamlfind", so it can be a program name with args.
+set dummy ocamlfind; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_OCAMLFIND+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$OCAMLFIND"; then
+  ac_cv_prog_OCAMLFIND="$OCAMLFIND" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_OCAMLFIND="ocamlfind"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_OCAMLFIND" && ac_cv_prog_OCAMLFIND="no"
+fi
+fi
+OCAMLFIND=$ac_cv_prog_OCAMLFIND
+if test -n "$OCAMLFIND"; then
+  { echo "$as_me:$LINENO: result: $OCAMLFIND" >&5
+echo "${ECHO_T}$OCAMLFIND" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+if test "$OCAMLFIND" != no; then
+    OUNITLIBDIR=`$OCAMLFIND query ounit`
+fi
+# then try ocamlopt -where
+if test "x$OUNITLIBDIR" = x; then
+    OUNITLIBDIR=`ocamlopt -where`
+    as_ac_File=`echo "ac_cv_file_"$OUNITLIBDIR/oUnit.mli"" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for \"$OUNITLIBDIR/oUnit.mli\"" >&5
+echo $ECHO_N "checking for \"$OUNITLIBDIR/oUnit.mli\"... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r ""$OUNITLIBDIR/oUnit.mli""; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: OUnit was not found with ocamlfind or in the ocaml library path.
+                  It is available at <http://www.xs4all.nl/~mmzeeman/ocaml/>." >&5
+echo "$as_me: error: OUnit was not found with ocamlfind or in the ocaml library path.
+                  It is available at <http://www.xs4all.nl/~mmzeeman/ocaml/>." >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
+EXTRALIBDIRS="$EXTRALIBDIRS $OUNITLIBDIR"
 
 #
 # ------------------- Perl ----------------
@@ -5829,6 +5913,7 @@ target!$target$ac_delim
 target_cpu!$target_cpu$ac_delim
 target_vendor!$target_vendor$ac_delim
 target_os!$target_os$ac_delim
+OCAMLFIND!$OCAMLFIND$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
@@ -5853,7 +5938,7 @@ EXTRALIBDIRS!$EXTRALIBDIRS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 81; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 82; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
